### ISSUE TITLE
3 GPU

### ISSUE THREAD

**Issue by chenbolinstudent** [STVIR/pysot#100]
when use 3 GPU ,how to change the parameters to get EAO=0.414 ?

**Comment by chenbolinstudent** [comment]
how to set batch_size 、 penalty_k 、window influence  ?
thanks.

**Comment by lb1100** [comment]
You need to test on your own. We can't provide configs for every combinations. Our experiments will be conducted mainly on 8/16 1080TIs. About hyper parameters, you can use [hp_search](https://github.com/STVIR/pysot/blob/master/tools/hp_search.py)

**Comment by yc-zc** [comment]
> can you explain why t batch_size 、 penalty_k 、window influence in GPU8 and GPU16 are different?
> thanks

The batch size should be set according to the availability of the total available memory of your GPU, and the reset parameters need to be adjusted by batch_size. 
Since this issue is not relevant to this repo, I'm closing it for now. I would personally suggest you search online for instructions on how to set the learning parameters.
