### ISSUE TITLE
Can I merge two branches in RPN into one, just like SSD header?

### ISSUE THREAD

**Issue by dypromise** [STVIR/pysot#141]
Hi, authors!
I want to make siamRPN to run realtime in CPU, so I try some versions siamRPN on it. but now I encountered  speed bottleneck when trying mobilenet-based siamRPN and  I found that there are 8 conv layers in RPN stage while most of these is not depthwise-conv, so it is time consuming, While  only 270 MFLOPS in backbone. Anyone have tryed merge two branches into one just like SSD header? SSD like header will save at least  a half convs in RPN header. SO IT HAS SOME MASKTAKES of WHAT I THINK? thanks for all explains！

**Comment by lb1100** [comment]
Do you have detail speed test on CPU about time cost of two parts? I think most time speeds on backbone, since dilated convs are really slow. Although there are eight convs in head, only four of them are 3x3 convs. The other four are 1x1 convs. So I don't think it will cost so much time.

About merging two parts, we tried, the performance will be a little worse than split. If you want faster speed, reducing channels of heads may be a better way.

**Comment by dypromise** [comment]
Thank you so much about your tips!
