### ISSUE TITLE
A problem about TRAIN.EXEMPLAR_SIZE and TRAIN.SEARCH_SIZE

### ISSUE THREAD

**Issue by liuyun19951104** [STVIR/pysot#164]
I want train the model in my own dataset. So I want to modify the  TRAIN.EXEMPLAR_SIZE and TRAIN.SEARCH_SIZE. However, I can't find the parameters in the config.yaml. But the code has use it. I want to know how to get it?

**Comment by liuyun19951104** [comment]
I have find the config.py and change it. However , there is another problem. I want to change the  EXEMPLAR_SIZE as 31. Then I run it, it run error :
Traceback (most recent call last):
  File "../../tools/train.py", line 319, in <module>
    main()
  File "../../tools/train.py", line 314, in main
    train(train_loader, dist_model, optimizer, lr_scheduler, tb_writer)
  File "../../tools/train.py", line 211, in train
    outputs = model(data)
  File "/home/liuyun2/anaconda3/envs/pysot/lib/python3.7/site-packages/torch/nn/modules/module.py", line 477, in __call__
    result = self.forward(*input, **kwargs)
RuntimeError: sizes must be non-negative
 Is there some rule to solute the problem?

**Comment by xxAna** [comment]
This is probably that the output a certain layer in the model is less than 0 since the input size is too small. I encounter a same problem and I print the output size of each layer of the model so as to found the resaon.To solve it, maybe you have to redesign the model to ensure each layer's output size is bigger than 0.

**Comment by xxAna** [comment]
> I have find the config.py and change it. However , there is another problem. I want to change the EXEMPLAR_SIZE as 31. Then I run it, it run error :
> Traceback (most recent call last):
> File "../../tools/train.py", line 319, in 
> main()
> File "../../tools/train.py", line 314, in main
> train(train_loader, dist_model, optimizer, lr_scheduler, tb_writer)
> File "../../tools/train.py", line 211, in train
> outputs = model(data)
> File "/home/liuyun2/anaconda3/envs/pysot/lib/python3.7/site-packages/torch/nn/modules/module.py", line 477, in **call**
> result = self.forward(*input, **kwargs)
> RuntimeError: sizes must be non-negative
> Is there some rule to solute the problem?
This is probably that the output a certain layer in the model is less than 0 since the input size is too small. I encounter a same problem and I print the output size of each layer of the model so as to found the resaon.To solve it, maybe you have to redesign the model to ensure each layer's output size is bigger than 0.
