### ISSUE TITLE
Discussion of Central Bias in Tracking with Deepnet

### ISSUE THREAD

**Issue by beihaifusang** [STVIR/pysot#176]
After reading SiamRPN++, I am still a little bit confused by the claim 
"padding destroy the strict translation invariance and thus cause the network to learn central bias and thus was not able to be utilized in tracking".

Specifically, my confusion lies in
1. why it is padding, rather than the non-linearity, that causes such a spatial bias? May I interpret in another way that the deep net has enough kernel to learn a spatial bias while the shallow net does not.

2. Or equivalently, could you please explain a little bit of how padding contributes to the central bias? 
(as I would imagine to overfit any regression network by feeding only label at center to it and thus cause it to have a central bias)

Any kind of help would be greatly appreciated.

**Comment by jhultman** [comment]
Here's my understanding. The fully convolutional networks are supposed to produce features that are translationally invariant. The algorithm should not be able to "tell" where a cell (i.e. pixel) is by inspecting its feature. If the algorithm can distinguish cells near the border from cells near the center, it may begin to rely on that information even though it is just a quirk of the dataset. The center-bias will not hold at inference time when the search region center is chosen based on imperfect target tracking.

If 'same' padding is used and there is no data augmentation to ensure border signal is an unreliable cue for objectness, the boundary pixels will suffer from accumulated border effects which allow the algorithm to tell them apart from the center pixels, and exploit the bias during training. The border effects are worse for deeper networks because the padded values creep further into the center because of large receptive field.

![convolve](https://user-images.githubusercontent.com/27909223/64733408-b6580600-d4b2-11e9-861f-ada930a2fce9.png)

**Comment by beihaifusang** [comment]
Ewww, I see. I used to think "spatial bias" as a bias to concrete location (e.g. i-th row j-th col in output space tends to be labelled as blablabla), and now I realize it refers to the concept of center-border-corner.
Yes, it is padding who provide the possibility for such a spatial bias. 
Thank you so much! :)
