### ISSUE TITLE
All the Siam tracker series cannot  judge  disappearance of target？

### ISSUE THREAD

**Issue by dongfangduoshou123** [STVIR/pysot#3]

**Comment by BaronH07** [comment]
The network itself cannot judge since it is not necessary to do so, but you can add selection criterions later since the score maps are able to indicate whether it believes the object is in the search region or not, so you can set a threshold for determining disappearance of objects from successful tracking.

**Comment by dongfangduoshou123** [comment]
但是我测试过用scoremap选阈值来判定的，结果如下:
 通过DaSiamRPN实际测试，发现DaSiamRPN对目标跟踪的位置更新非常鲁棒，比如测试高速场景下DaSiamRPN跟车，测试了多种环境（正常白天，夜晚，恶劣天气）位置更新都挺好，没有漂移现象。
但是有个问题就是跟的目标（车）实际消失了，通过DaSiamRPN输出的Box best_score设定一个阈值，判断目标消失，停止对该目标的跟踪，发现这个best_score做不到，目标消失了，best_score基本不降，过一会还会升上去甚至比最初的目标在的时候best_score还高;

是不是可以理解为：DaSiamRPN的box best_score只是给出了位置的最佳更新选择，没有关注该位置是真正的目标还是背景的问题？如果能再输出一个score代表该位置是真正的目标还是背景的得分就好了！
很多实际落地的应用跟踪的场景，目标在的时候能跟上，目标消失也能得知才行。

**Comment by lb1100** [comment]
I believe long term module will solve your problems. We provided a long term model in [siamrpn_r50_l234_dwxcorr_lt](https://github.com/STVIR/pysot/tree/master/experiments/siamrpn_r50_l234_dwxcorr_lt). This is described in DaSiamRPN's long term section.

**Comment by dongfangduoshou123** [comment]
好的，我试试，谢谢！
期待开源个pymot。👍👍👍

**Comment by dongfangduoshou123** [comment]
siamrpn_r50_l234_dwxcorr_lt's speed 20 fps, a bit slow.
抛开打比赛，给常规Siam系列的tracker添加判断目标消失的输出是一个方向， 很实用。
类似于ATOM可以输出‘not_found’的那种。
